#!/bin/bash

set -e
set -v

function clear () {
    echo -ne "\x1B[0m\x1B[H\x1B[J\x1B[3J"
}

function blue-bar () {
    echo -e "\r\x1B[1;37;44m$*\x1B[K\x1B[0m" 1>&2
}

LIGHTFIELD_SRC=/home/lumen/Volumetric/LightField
USBDRIVER_SRC=${LIGHTFIELD_SRC}/usb-driver
PRINTRUN_SRC=/home/lumen/Volumetric/printrun
if [ "$1" = "-q" ]
then
    VERBOSE=
else
    VERBOSE=-v
fi

clear

#blue-bar • Building debugging version of set-projector-power
#cd ${USBDRIVER_SRC}
#[ -f set-projector-power ] && rm ${VERBOSE} -f set-projector-power
#g++ -o set-projector-power -pipe -g -Og -D_DEBUG -std=gnu++1z -Wall -W -D_REENTRANT -fPIC -lhidapi-libusb dlpc350_usb.cpp dlpc350_api.cpp main.cpp

blue-bar • Building debugging version of LightField
cd ${LIGHTFIELD_SRC}
./rebuild -x

blue-bar • Creating directories
[ ! -d /var/cache/lightfield/print-jobs     ] && mkdir ${VERBOSE} -p /var/cache/lightfield/print-jobs
[ ! -d /var/lib/lightfield/model-library    ] && mkdir ${VERBOSE} -p /var/lib/lightfield/model-library
[ ! -d /var/lib/lightfield/software-updates ] && mkdir ${VERBOSE} -p /var/lib/lightfield/software-updates
[ ! -d /var/log/lightfield                  ] && mkdir ${VERBOSE} -p /var/log/lightfield

chown -Rc lumen:lumen /var/cache/lightfield
chown -Rc lumen:lumen /var/lib/lightfield
chown -Rc lumen:lumen /var/log/lightfield

blue-bar • Installing files
install ${VERBOSE} -DT -m 440    system-stuff/lumen-lightfield                       /etc/sudoers.d/lumen-lightfield
install ${VERBOSE} -DT -m 644    system-stuff/getty@tty1.service.d_override.conf     /etc/systemd/system/getty@tty1.service.d/override.conf
install ${VERBOSE} -DT -m 644    system-stuff/lumen-bash_profile                     /home/lumen/.bash_profile
install ${VERBOSE} -DT -m 644    system-stuff/lightfield.service                     /lib/systemd/system/lightfield.service
install ${VERBOSE} -DT -m 644    usb-driver/90-dlpc350.rules                         /lib/udev/rules.d/90-dlpc350.rules
install ${VERBOSE} -DT -m 755 -s build/lf                                            /usr/bin/lf
#install ${VERBOSE} -DT -m 755 -s set-projector-power                                 /usr/bin/set-projector-power
install ${VERBOSE} -DT -m 755    /usr/local/bin/setpower                             /usr/bin/set-projector-power
install ${VERBOSE} -DT -m 644    stdio-shepherd/printer.py                           /usr/share/lightfield/libexec/stdio-shepherd/printer.py
install ${VERBOSE} -DT -m 755    stdio-shepherd/stdio-shepherd.py                    /usr/share/lightfield/libexec/stdio-shepherd/stdio-shepherd.py
install ${VERBOSE} -DT -m 755    system-stuff/reset-lumen-arduino-port               /usr/share/lightfield/libexec/reset-lumen-arduino-port
install ${VERBOSE} -DT -m 755    system-stuff/upgrade-lumenx-firmware                /usr/share/lightfield/libexec/upgrade-lumenx-firmware
install ${VERBOSE} -DT -m 644    system-stuff/99-waveshare.conf                      /usr/share/X11/xorg.conf.d/99-waveshare.conf

cd ${PRINTRUN_SRC}
install ${VERBOSE} -DT -m 644    printrun/__init__.py                               /usr/share/lightfield/libexec/printrun/printrun/__init__.py
install ${VERBOSE} -DT -m 644    printrun/eventhandler.py                           /usr/share/lightfield/libexec/printrun/printrun/eventhandler.py
install ${VERBOSE} -DT -m 644    printrun/gcoder.py                                 /usr/share/lightfield/libexec/printrun/printrun/gcoder.py
install ${VERBOSE} -DT -m 644    printrun/printcore.py                              /usr/share/lightfield/libexec/printrun/printrun/printcore.py
install ${VERBOSE} -DT -m 644    printrun/utils.py                                  /usr/share/lightfield/libexec/printrun/printrun/utils.py
install ${VERBOSE} -DT -m 644    printrun/plugins/__init__.py                       /usr/share/lightfield/libexec/printrun/printrun/plugins/__init__.py
install ${VERBOSE} -DT -m 644    Util/constants.py                                  /usr/share/lightfield/libexec/printrun/Util/constants.py


blue-bar • Configuring system
systemctl daemon-reload
systemctl enable getty@tty1.service
systemctl enable lightfield.service
systemctl set-default multi-user.target
