#!/bin/bash

function clear () {
    echo -ne "\x1B[0m\x1B[H\x1B[J\x1B[3J"
}

function blue-bar () {
    echo -e "\r\x1B[1;37;44m$*\x1B[K\x1B[0m"
}

VERSION=1.0.1

PACKAGE_BUILD_ROOT=/code/work/Volumetric/LightField/mk7
LIGHTFIELD_SRC=/home/lumen/Volumetric/LightField
LIGHTFIELD_PACKAGE=${PACKAGE_BUILD_ROOT}/lightfield-${VERSION}

cd {$PACKAGE_BUILD_ROOT}

blue-bar • Creating LightField ${VERSION} release build update kit
tar                                                               \
    -vv                                                           \
    -C ${PACKAGE_BUILD_ROOT}                                      \
    -c                                                            \
    -f lightfield-release_${VERSION}_amd64.kit                    \
    --owner=root                                                  \
    --group=root                                                  \
    fonts-montserrat_7.200_all.deb                                \
    lightfield-common_${VERSION}_amd64.deb                        \
    lightfield-firmware_${VERSION}_all.deb                        \
    lightfield-release_${VERSION}_amd64.deb

blue-bar • Signing release build update kit
gpg                                                               \
    --detach-sign                                                 \
    --local-user 'lightfield-packager@volumetricbio.com'          \
    --verbose                                                     \
    --output lightfield-release_${VERSION}_amd64.kit.sig          \
    ${PACKAGE_BUILD_ROOT}/lightfield-release_${VERSION}_amd64.kit

blue-bar • Creating LightField ${VERSION} debug build update kit
tar                                                               \
    -vv                                                           \
    -C ${PACKAGE_BUILD_ROOT}                                      \
    -c                                                            \
    -f lightfield-debug_${VERSION}_amd64.kit                      \
    --owner=root                                                  \
    --group=root                                                  \
    fonts-montserrat_7.200_all.deb                                \
    lightfield-common_${VERSION}_amd64.deb                        \
    lightfield-firmware_${VERSION}_all.deb                        \
    lightfield-debug_${VERSION}_amd64.deb                         \
    lightfield-debug-dbgsym_${VERSION}_amd64.deb

blue-bar • Signing debug build update kit
gpg                                                               \
    --detach-sign                                                 \
    --local-user 'lightfield-packager@volumetricbio.com'          \
    --verbose                                                     \
    --output lightfield-debug_${VERSION}_amd64.kit.sig            \
    ${PACKAGE_BUILD_ROOT}/lightfield-debug_${VERSION}_amd64.kit
