#!/usr/bin/env bash

[ -z "${BUILDDIR}" ] && export BUILDDIR="/home/lumen/Volumetric/LightField/build"

function usage () {
    cat <<HERE
Usage: rebuild [-cnqrx] [--clean|--nuke-first|--qmake-anyway|--release]
Runs "qmake" to regenerate the Makefile, if necessary, then "make" to
rebuild LightField.

  -c,     --clean          Run "make distclean" before running "make".
  -n, -x, --nuke-first     Delete and recreate the build directory before
                             running "make".
  -q,     --qmake-anyway   Run "qmake" even if timestamps suggest it
                             shouldn't be necessary.
  -r,     --release        Perform a release build instead of a debug
                             build.
HERE
}

function rebuild () {
    local BUILD=debug
    local CLEAN=
    local NUKE=
    local QMAKE=
    local ARGS=
    local LASTBUILDMODE=

    if ! getopt -Q -q -n 'rebuild' -o 'cnqrx' -l 'clean,nuke-first,qmake-anyway,release' -- "$@"; then
        usage
        return
    fi

    ARGS=$(getopt -n 'rebuild' -o 'cnqrx' -l 'clean,nuke-first,qmake-anyway,release' -- "$@")
    eval set -- "$ARGS"

    while [ -n "${1}" ]
    do
        case "${1}" in
            '-c'        | '--clean'        ) CLEAN=yes     ;;
            '-n' | '-x' | '--nuke-first'   )  NUKE=yes     ;;
            '-q'        | '--qmake-anyway' ) QMAKE=yes     ;;
            '-r'        | '--release'      ) BUILD=release ;;

            '--' )
                shift
                break
                ;;

            * )
                return
                ;;
        esac
        shift
    done

    if [ -d "${BUILDDIR}" ]
    then
        if [ ! -f "${BUILDDIR}/.lastbuildmode" ]
        then
            echo "${BUILD}" > "${BUILDDIR}/.lastbuildmode"
            NUKE=yes
        fi

        LASTBUILDMODE="$(<${BUILDDIR}/.lastbuildmode)"
        if [ -n "${LASTBUILDMODE}" ] && [ "${BUILD}" != "${LASTBUILDMODE}" ]
        then
            echo Switching from "${LASTBUILDMODE}" to "${BUILD}".
            NUKE=yes
        fi

        if [ -n "${NUKE}" ]
        then
            unset CLEAN
            QMAKE=yes
            rm -dr "${BUILDDIR}" && mkdir -p "${BUILDDIR}"
        fi
    else
        mkdir -p "${BUILDDIR}"
    fi

    cd "${BUILDDIR}"

    if [ -n "${CLEAN}" ]
    then
        QMAKE=yes
        make distclean
    fi

    if [ -n "${QMAKE}" ] || [ ! -f Makefile ] || [ ../qt/lf.pro -nt Makefile ]
    then
        qmake CONFIG+="${BUILD}" ../qt/lf.pro || return
        echo "${BUILD}" > "${BUILDDIR}/.lastbuildmode"
    fi

    if make -q 1> /dev/null 2>&1
    then
        echo "make: Nothing to be done for 'first'."
        return
    fi

    rm buildinfo.o 1> /dev/null 2>&1
    make -j"${QT_BUILD_JOBS-12}"
}

rebuild $*
