#include <cmath>
#include <cstdlib>

#include <future>
#include <vector>

#include <QApplication>
#include <QDataStream>
#include <QDebug>
#include <QFile>
#include <QFileSystemModel>
#include <QGridLayout>
#include <QHBoxLayout>
#include <QLabel>
#include <QLineEdit>
#include <QListView>
#include <QMainWindow>
#include <QMouseEvent>
#include <QOpenGLBuffer>
#include <QOpenGLFunctions>
#include <QOpenGLShaderProgram>
#include <QPalette>
#include <QPixmap>
#include <QProcess>
#include <QPushButton>
#include <QSlider>
#include <QString>
#include <QStringListModel>
#include <QSurfaceFormat>
#include <QTabWidget>
#include <QtDebug>
#include <QThread>
#include <QTimer>
#include <QtOpenGL>
#include <QtOpenGL/QtOpenGL>
#include <QVBoxLayout>
#include <QVector3D>
#include <QWidget>
